version: "3.9"
services:
  books_service:
    build:
      context: ./books_service
      dockerfile: Dockerfile
    env_file:
      - ./books_service/.env
  students_service:
    build:
      context: ./students_service
      dockerfile: Dockerfile
    env_file:
      - ./students_service/.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    port:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - books_service
      - students_service
